site:
  name: Samuel Almeida
  site: 'http://localhost:4321'
  base: '/'
  trailingSlash: false

metadata:
  title:
    default: Samuel Almeida
    template: '%s'
  description: 'Portfolio website of Samuel Almeida.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Samuel Almeida
    images: []
    type: website
  twitter:
    handle: ''
    site: ''
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 0

    post:
      isEnabled: false
      permalink: '/%slug%'
      robots:
        index: false

    list:
      isEnabled: false
      pathname: 'blog'
      robots:
        index: false

    category:
      isEnabled: false
      pathname: 'category'
      robots:
        index: false

    tag:
      isEnabled: false
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 0

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
